Working init.d service script

diff --git a/express-proxy b/express-proxy
--- a/express-proxy
+++ b/express-proxy
@@ -15,13 +15,13 @@ ERROR_LOG=/var/log/express-proxy/error.log
 case "$1" in
 	start)
     cd $INSTALL_DIR
-    exec npm install --save &
-	exec npm run dev 1>>$PROXY_LOG 2>>$ERROR_LOG &
+    exec npm install --save 1>> $PROXY_LOG 2>> $ERROR_LOG &
+	exec npm run dev 1>> $PROXY_LOG 2>> $ERROR_LOG &
 	;;
 
 	stop)
 	echo "Received shutdown signal from init.d. Exiting." >> $PROXY_LOG
-	kill $(ps aux | grep 'eproxy' | awk '{print $2}')
+	kill $(ps aux | grep 'eproxy' | grep -v grep | awk '{print $2}') || echo "Error killing eproxy" >> $ERROR_LOG
 	;;
 esac
 exit 0
